name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with v (e.g., v1.0.0)

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle
      
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      
      - name: Build plugin
        run: ./gradlew buildPlugin
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Find distribution ZIP
        id: find_zip
        run: |
          ZIP_FILE=$(find ./build/distributions/ -name "*.zip" | head -n 1)
          echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_OUTPUT
          echo "ZIP_NAME=$(basename $ZIP_FILE)" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          files: ${{ steps.find_zip.outputs.ZIP_FILE }}
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
      
      - name: Update latest tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Delete 'latest' tag if it exists
            try {
              await github.rest.git.deleteRef({
                owner,
                repo,
                ref: 'tags/latest'
              });
              console.log("Deleted existing 'latest' tag");
            } catch (error) {
              console.log("No existing 'latest' tag found or could not delete it");
            }
            
            // Get SHA of current tag
            const tagRef = await github.rest.git.getRef({
              owner,
              repo,
              ref: `tags/${context.ref.replace('refs/tags/', '')}`
            });
            
            // Create new 'latest' tag pointing to same commit
            await github.rest.git.createRef({
              owner,
              repo,
              ref: 'refs/tags/latest',
              sha: tagRef.data.object.sha
            });
            console.log("Created new 'latest' tag");